#!/usr/local/bin/gosh
(use net.twitter)
(define (main args)
  (let ()
	(display "Enter consumer key: ") (flush)
	(let1 key (read-line)
		  (when (eof-object? key) (exit 1 "aborted."))
		  (display "Enter consumer secret: ") (flush)
		  (let1 secret (read-line)
				(when (eof-object? secret) (exit 1 "aborted."))
				(report (twitter-authenticate-client key secret))))))
(define (report cred)
  (print "(")
  (print " (consumer-key        = \""(ref cred'consumer-key)"\")")
  (print " (consumer-secret     = \""(ref cred'consumer-secret)"\")")
  (print " (access-token        = \""(ref cred'access-token)"\")")
  (print " (access-token-secret = \""(ref cred'access-token-secret)"\")")
  (print ")"))
